### ISSUE TITLE
DELETE BOOK ISSUE 

### ISSUE THREAD

**Issue by DanishAzeema** [subinkhanal/Library-management-system#1]
![issue tracking1](https://user-images.githubusercontent.com/81403168/117774835-99f90780-b259-11eb-8611-bd8d6ff2f904.png)
![issue tracking2](https://user-images.githubusercontent.com/81403168/117774851-9e252500-b259-11eb-9277-8e8444e8d361.png)

The delete option of the book post page is running into an error.
@subinkhanal  hope you will fix this issue.

**Comment by subinkhanal** [comment]
![image](https://user-images.githubusercontent.com/61418023/118365682-977e1100-b5bd-11eb-9faf-c2d2bbe6a585.png)
