### ISSUE TITLE
Navigation Bar and Footer in Web Page

### ISSUE THREAD

**Issue by dristi-sigdel** [subinkhanal/Library-management-system#10]
There must be navigation bar and footer in every web pages of web site.
![image](https://user-images.githubusercontent.com/81402784/118351998-bb6e3200-b57e-11eb-870b-7dd565a9808f.png)

**Comment by subinkhanal** [comment]
![image](https://user-images.githubusercontent.com/61418023/118355578-663b1c00-b590-11eb-8080-3c38063981ff.png)
i have solve this issue successfully done
