### ISSUE TITLE
Redesign Contact Page

### ISSUE THREAD

**Issue by dristi-sigdel** [subinkhanal/Library-management-system#11]
Contact information should be more visible and color scheme should match with other web pages.
![image](https://user-images.githubusercontent.com/81402784/118352416-0db05280-b581-11eb-9031-a9a8ff7a7c55.png)

**Comment by saman-des** [comment]
![Screenshot 2021-05-15 194342](https://user-images.githubusercontent.com/59384040/118363863-0e171080-b5b6-11eb-8ae4-1e6c3889ae2e.png)
You can see the new contact page in full as I have already pushed it. I am closing this issue.
