### ISSUE TITLE
BOOK VIEW INTERFACE

### ISSUE THREAD

**Issue by DanishAzeema** [subinkhanal/Library-management-system#12]
The interface of the book view is not good. @saman-des  can you please change the interface.
![issue3](https://user-images.githubusercontent.com/81403168/118355607-984c7e00-b590-11eb-80e9-074b6c2fcc1e.png)

**Comment by saman-des** [comment]
I have updated the interface and the image is also showing.
![Screenshot 2021-05-15 193652](https://user-images.githubusercontent.com/59384040/118363624-f4c19480-b5b4-11eb-8446-a15f4d7605a4.png)
I have discussed with danish and he is satisfied with it. Thus I will close this issue :)
