### ISSUE TITLE
IMAGE NOT LOADING

### ISSUE THREAD

**Issue by DanishAzeema** [subinkhanal/Library-management-system#13]
There is an issue in submitting the images in the Novel Portion. MR. Susan Shrestha @9841412881,  can you please fix the issue. 
![issue4](https://user-images.githubusercontent.com/81403168/118355754-74d60300-b591-11eb-9520-cc697b1bf71e.png)

**Comment by hasty-bloke** [comment]
![Screenshot (224)](https://user-images.githubusercontent.com/81402735/118362363-fb4d0d80-b5ae-11eb-8d26-51c888acafb7.png)
The request has been made to subject and the ticket is close @DanishAzeema
