### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by dristi-sigdel** [subinkhanal/Library-management-system#15]
The search function is not working. It would be better if developers can make it work. However, any alternatives for search can be useful as well.
![image](https://user-images.githubusercontent.com/81402784/118357507-427cd380-b59a-11eb-8065-188a9a5db1c5.png)

**Comment by subinkhanal** [comment]
![image](https://user-images.githubusercontent.com/61418023/118365384-4de0f680-b5bc-11eb-97ef-f6e5b48b0e5f.png)
