### ISSUE TITLE
Interface for gallery

### ISSUE THREAD

**Issue by dristi-sigdel** [subinkhanal/Library-management-system#16]
The interface for gallery page should b redesigned.
![image](https://user-images.githubusercontent.com/81402784/118366036-d496d300-b5be-11eb-9564-ab04f2846e32.png)

**Comment by saman-des** [comment]
I have made amends to the gallery page and have also pushed it. I have fixed the issue and am closing the issue.
![image](https://user-images.githubusercontent.com/59384040/118371894-60642b80-b5ce-11eb-88cf-b976f7613631.png)
