### ISSUE TITLE
Dashboard Interface

### ISSUE THREAD

**Issue by dristi-sigdel** [subinkhanal/Library-management-system#18]
The interface of dashboard should be redesigned.
![image](https://user-images.githubusercontent.com/81402784/118373861-af16c300-b5d8-11eb-880a-898ec6154e3f.png)

**Comment by saman-des** [comment]
![image](https://user-images.githubusercontent.com/59384040/118373922-fe5cf380-b5d8-11eb-9973-fbec788bdfc4.png)
<img src="https://user-images.githubusercontent.com/59384040/118374057-cb672f80-b5d9-11eb-9c33-d92a31a3b620.png" width="200" height="300">

Here is the changes in regards to the dashboard interface.
Main changes: Color scheme matches with other web pages,  responsive design, changes to the logo, changes to the button and several alignment changes
I have fixed the design bugs and will close this issue.
