### ISSUE TITLE
Poor Interface Design

### ISSUE THREAD

**Issue by dristi-sigdel** [subinkhanal/Library-management-system#2]
Interface for Login page should be redesigned to be more accessible.

![image](https://user-images.githubusercontent.com/81402784/117829547-9635a700-b292-11eb-88f2-e9798f913133.png)

**Comment by saman-des** [comment]
Here is the updated interface for login page.
![Screenshot (82)](https://user-images.githubusercontent.com/59384040/118273618-dcce1000-b4e3-11eb-8c53-01640175336b.png)
And here is the updated interface of the registered page.
![Screenshot (84)](https://user-images.githubusercontent.com/59384040/118273623-dfc90080-b4e3-11eb-982f-e0de8ea630f5.png)
Hope the interface is better and let me know if there are other issues.
