### ISSUE TITLE
Index page interface redesign

### ISSUE THREAD

**Issue by dristi-sigdel** [subinkhanal/Library-management-system#4]
The interface design is not good enough. It should contain consistency and high accessibility.
![image](https://user-images.githubusercontent.com/81402784/118291102-edd44c80-b4f6-11eb-8118-aac658c90f40.png)

**Comment by Purnima117** [comment]
I had tried to do my best to improve the interface design of the index page.  
![Screenshot (866)](https://user-images.githubusercontent.com/81402841/118302406-e5ced980-b503-11eb-8b8c-ee8f187781d4.png)
